config/routes.rb
LanguageMap::Application.routes.draw do

  root to: 'data#map'

  resource :data, only: [:show] do
    collection do
      post :upload_csv
      get  :map
      get  :map_json
    end
  end

  resources :repositories, only: :index

end

app/models/csv_importer.rb
require 'csv'

class CsvImporter

  def self.import(csv)
    CSV.parse(File.read(csv)) do |row|
      r = Repository.new
      r.sha = row[0] unless row[0] == "null"
      r.url = row[1] unless row[1] == "null"
      r.language = row[2] unless row[2] == "null"
      r.location = row[3..-1].join(",") unless row[3] == "null"
      r.save
    end
  end
end

app/models/latlong_populator.rb
class LatlongPopulator
  def run
    repositories.each do |repo|
      puts "Finding #{repo.location}...\n"
      location = force_encoding_for(repo.location)
      lat, lng = Geocoder.coordinates(location)
      repo.update_attributes latitude: lat, longitude: lng if lat && lng
    end
  end

  private

  def repositories
    Repository.where("latitude IS NULL AND longitude IS NULL")
  end

  def force_encoding_for(location)
    location.force_encoding("binary").encode("UTF-8",
                                             invalid: :replace,
                                             undef:   :replace,
                                             replace: ""
                                            )
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  validates :sha, presence: true, uniqueness: true
  validates :url, presence: true
  validates :language, presence: true
  validates :location, presence: true

  def self.has_latlong
    self.where("latitude IS NOT NULL AND longitude IS NOT NULL")
  end

  def self.languages
    self.distinct.pluck(:language)
  end

  def self.in_language(language)
    self.where(language: language)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def show
  end

  def upload_csv
    CsvImporter.import(params[:file].path)
    flash[:notice] = "File uploaded"
    redirect_to data_path
  end

  def map
  end

  def map_json
    data = File.read('vendor/json/world-50m.json')
    render json: data
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    render json: Repository.has_latlong
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data/map.html.erb
<div id='container'>
  <div id='map'></div>
  <div>
    <ul id='key'>
      <li><%= check_box_tag 'Ruby', nil, true %><span id="red"></span> Ruby</li>
      <li><%= check_box_tag 'JavaScript', nil, true %><span id="green"></span> JavaScript</li>
      <li><%= check_box_tag 'Python', nil, true %><span id="blue"></span> Python</li>
      <li><%= check_box_tag 'Java', nil, true %><span id="yellow"></span> Java</li>
      <li><%= check_box_tag 'CSS', nil, true %><span id="purple"></span> CSS</li>
      <li><%= check_box_tag 'C++', nil, true %><span id="orange"></span>C++</li>
      <li><%= check_box_tag 'PHP', nil, true %><span id="brown"></span>PHP</li>
      <li><%= check_box_tag 'Shell', nil, true %><span id="indigo"></span>Shell</li>
      <li><%= check_box_tag 'C', nil, true %><span id="pink"></span>C</li>
      <li><%= check_box_tag 'Objective-C', nil, true %><span id="aqua"></span>Objective-C</li>
    </ul>
  </div>
</div>

app/views/data/show.html.erb
<%= form_tag upload_csv_data_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LanguageMap</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>